"""Contratos estáveis dos eventos de domínio do MVP."""

from app.events.catalog import (
    EVENT_CATALOG,
    AggregateType,
    AppliedCouponPayload,
    AuthenticationCompletedPayload,
    AuthenticationSessionPayload,
    AvailabilityChangedPayload,
    CollectionCompletedPayload,
    CollectionFailedPayload,
    EventCatalogError,
    EventSpec,
    EventType,
    MissionPrelistErrataPayload,
    MissionPrelistErrataV2Payload,
    MissionPrelistReadyPayload,
    MissionPrelistReadyV2Payload,
    MissionStatusChangedPayload,
    MissionVariantsReadyPayload,
    PrelistOfferPayload,
    PriceDecreasedPayload,
    PriceTargetReachedPayload,
    ProductVariantOptionPayload,
    resolve_event_spec,
    validate_event_payload,
)
from app.events.consumption import (
    EventConsumptionError,
    claim_unconsumed_events,
    count_failed_attempts,
    record_consumption_attempt,
)
from app.events.models import ConsumptionOutcome, Event, EventConsumptionAttempt
from app.events.service import EventPublicationError, publish_event

__all__ = [
    "EVENT_CATALOG",
    "AggregateType",
    "AppliedCouponPayload",
    "AuthenticationCompletedPayload",
    "AuthenticationSessionPayload",
    "AvailabilityChangedPayload",
    "CollectionCompletedPayload",
    "CollectionFailedPayload",
    "ConsumptionOutcome",
    "Event",
    "EventCatalogError",
    "EventConsumptionAttempt",
    "EventConsumptionError",
    "EventPublicationError",
    "EventSpec",
    "EventType",
    "MissionPrelistErrataPayload",
    "MissionPrelistErrataV2Payload",
    "MissionPrelistReadyPayload",
    "MissionPrelistReadyV2Payload",
    "PrelistOfferPayload",
    "MissionStatusChangedPayload",
    "MissionVariantsReadyPayload",
    "PriceDecreasedPayload",
    "PriceTargetReachedPayload",
    "ProductVariantOptionPayload",
    "claim_unconsumed_events",
    "count_failed_attempts",
    "publish_event",
    "record_consumption_attempt",
    "resolve_event_spec",
    "validate_event_payload",
]
